spring:
  application:
    name: StarWarsUniverse
  datasource:
    url: jdbc:h2:mem:universe
    username: sa
    password: pw
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 7100
